import type { CaseStudy, Faq, Location, Repair, Service, Training } from "./types";

const timestamp = "2025-01-01T00:00:00.000Z";

export const fallbackLocation: Location = {
  id: 1,
  name: "Addict AI Technology",
  address_line1: "Immeuble les Mimosas",
  postal_code: "20213",
  city: "Folelli",
  region: "Corse",
  country: "FR",
  phone: "+33 4 95 31 12 90",
  email: "contact@addictai.tech",
  geo_lat: 42.4474697,
  geo_lng: 9.5067658,
  google_maps_url: "https://www.google.com/maps?q=42.4474697,9.5067658",
  opening_hours: {
    mon: [{ open: "09:00", close: "18:00" }],
    tue: [{ open: "09:00", close: "18:00" }],
    wed: [{ open: "09:00", close: "18:00" }],
    thu: [{ open: "09:00", close: "18:00" }],
    fri: [{ open: "09:00", close: "18:00" }],
    sat: [{ open: "10:00", close: "16:00" }],
  },
  createdAt: timestamp,
  updatedAt: timestamp,
};

export const fallbackRepairs: Repair[] = [
  {
    id: 1,
    device_brand: "Apple",
    device_model: "iPhone 13",
    repair_type: "Écran",
    price_from: 149,
    duration_text: "60-90 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: true,
    sort_order: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 2,
    device_brand: "Apple",
    device_model: "iPhone 13",
    repair_type: "Batterie",
    price_from: 79,
    duration_text: "45-60 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 2,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 3,
    device_brand: "Apple",
    device_model: "iPhone 12",
    repair_type: "Écran",
    price_from: 139,
    duration_text: "60-90 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: true,
    sort_order: 3,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 4,
    device_brand: "Apple",
    device_model: "iPhone 12",
    repair_type: "Connecteur",
    price_from: 69,
    duration_text: "60-90 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 4,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 5,
    device_brand: "Samsung",
    device_model: "Galaxy S22",
    repair_type: "Écran",
    price_from: 169,
    duration_text: "60-90 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: true,
    sort_order: 5,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 6,
    device_brand: "Samsung",
    device_model: "Galaxy S22",
    repair_type: "Batterie",
    price_from: 89,
    duration_text: "45-60 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 6,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 7,
    device_brand: "Samsung",
    device_model: "Galaxy A52",
    repair_type: "Écran",
    price_from: 119,
    duration_text: "60-90 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 7,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 8,
    device_brand: "Samsung",
    device_model: "Galaxy A52",
    repair_type: "Batterie",
    price_from: 69,
    duration_text: "45-60 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 8,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 9,
    device_brand: "Xiaomi",
    device_model: "Redmi Note 12",
    repair_type: "Écran",
    price_from: 89,
    duration_text: "60-90 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 9,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 10,
    device_brand: "Xiaomi",
    device_model: "Redmi Note 12",
    repair_type: "Batterie",
    price_from: 59,
    duration_text: "45-60 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 10,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 11,
    device_brand: "Huawei",
    device_model: "P30",
    repair_type: "Écran",
    price_from: 109,
    duration_text: "60-90 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 11,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 12,
    device_brand: "Huawei",
    device_model: "P30",
    repair_type: "Connecteur",
    price_from: 59,
    duration_text: "45-60 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 12,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 13,
    device_brand: "Google",
    device_model: "Pixel 7",
    repair_type: "Écran",
    price_from: 179,
    duration_text: "60-120 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 13,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 14,
    device_brand: "Google",
    device_model: "Pixel 7",
    repair_type: "Batterie",
    price_from: 89,
    duration_text: "60-90 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 14,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 15,
    device_brand: "OnePlus",
    device_model: "9 Pro",
    repair_type: "Écran",
    price_from: 159,
    duration_text: "60-120 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 15,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 16,
    device_brand: "OnePlus",
    device_model: "9 Pro",
    repair_type: "Batterie",
    price_from: 79,
    duration_text: "60-90 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 16,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 17,
    device_brand: "Apple",
    device_model: "iPhone 11",
    repair_type: "Écran",
    price_from: 119,
    duration_text: "60-90 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 17,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 18,
    device_brand: "Apple",
    device_model: "iPhone 11",
    repair_type: "Batterie",
    price_from: 69,
    duration_text: "45-60 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 18,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 19,
    device_brand: "Samsung",
    device_model: "Galaxy S21",
    repair_type: "Écran",
    price_from: 159,
    duration_text: "60-90 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 19,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 20,
    device_brand: "Samsung",
    device_model: "Galaxy S21",
    repair_type: "Batterie",
    price_from: 79,
    duration_text: "45-60 min",
    warranty_text: "6 mois",
    notes: "",
    is_featured: false,
    sort_order: 20,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const fallbackFaqsB2C: Faq[] = [
  {
    id: 1,
    scope: "b2c",
    question: "Combien coûte une réparation d'écran iPhone ?",
    answer:
      "Les tarifs varient selon le modèle. Consultez notre grille tarifaire ou contactez-nous pour un devis gratuit.",
    sort_order: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 2,
    scope: "b2c",
    question: "Quel est le délai de réparation ?",
    answer:
      "La plupart des réparations sont effectuées en 30 à 90 minutes. Les interventions complexes peuvent prendre 24 à 48h.",
    sort_order: 2,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 3,
    scope: "b2c",
    question: "Mes données sont-elles en sécurité ?",
    answer:
      "Oui. Nous ne touchons jamais à vos données personnelles. Nous recommandons toutefois une sauvegarde préventive.",
    sort_order: 3,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 4,
    scope: "b2c",
    question: "Proposez-vous une garantie ?",
    answer: "Oui, toutes nos réparations sont garanties 6 mois pièces et main d'oeuvre.",
    sort_order: 4,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 5,
    scope: "b2c",
    question: "Faut-il prendre rendez-vous ?",
    answer:
      "Non, vous pouvez venir sans rendez-vous. Un RDV garantit une prise en charge immédiate.",
    sort_order: 5,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 6,
    scope: "b2c",
    question: "Quelles marques réparez-vous ?",
    answer:
      "Apple, Samsung, Huawei, Xiaomi, OnePlus, Google Pixel, et la plupart des marques courantes.",
    sort_order: 6,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const fallbackFaqsB2B: Faq[] = [
  {
    id: 10,
    scope: "b2b",
    question: "Quels sont les délais pour un projet d'automatisation ?",
    answer:
      "Un projet simple prend 1 à 2 semaines. Les projets complexes peuvent s'étaler sur 1 à 3 mois.",
    sort_order: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 11,
    scope: "b2b",
    question: "Proposez-vous de la maintenance ?",
    answer:
      "Oui, nous proposons des contrats de maintenance et support pour assurer le bon fonctionnement.",
    sort_order: 2,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 12,
    scope: "b2b",
    question: "Mes données sont-elles confidentielles ?",
    answer: "Oui. Nous pouvons signer un NDA et respectons le RGPD.",
    sort_order: 3,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 13,
    scope: "b2b",
    question: "Quels outils utilisez-vous ?",
    answer:
      "Make, Zapier, Airtable, Notion, n8n, ChatGPT API, et d'autres selon vos besoins.",
    sort_order: 4,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 14,
    scope: "b2b",
    question: "Proposez-vous du financement pour les formations ?",
    answer:
      "Selon votre situation, plusieurs dispositifs de prise en charge peuvent être étudiés. Contactez-nous pour en discuter.",
    sort_order: 5,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 15,
    scope: "b2b",
    question: "Travaillez-vous uniquement en Corse ?",
    answer:
      "Non, nous travaillons avec des clients dans toute la France, principalement à distance.",
    sort_order: 6,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const fallbackServices: Service[] = [
  {
    id: 1,
    title: "Audit & Roadmap",
    slug: "audit-roadmap",
    category: "Audit",
    summary:
      "Analyse des process, scoring ROI et feuille de route priorisée sur 90 jours.",
    description: "",
    deliverables: [
      "Audit des process existants",
      "Recommandations priorisees",
      "Roadmap a 90 jours",
    ],
    duration_estimate: "1-2 semaines",
    starting_price_text: "À partir de 1 200€",
    cta_label: "Demander un audit",
    cta_link: "/pro#audit",
    sort_order: 1,
    seo_title: "",
    seo_description: "",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 2,
    title: "Automatisation",
    slug: "automatisation",
    category: "Automation",
    summary:
      "Workflows robustes, intégrations API et automatisations IA pour gagner des heures.",
    description: "",
    deliverables: [
      "Workflows automatisés",
      "Intégrations API",
      "Documentation & formation",
    ],
    duration_estimate: "2-6 semaines",
    starting_price_text: "À partir de 2 500€",
    cta_label: "Automatiser mes process",
    cta_link: "/pro",
    sort_order: 2,
    seo_title: "",
    seo_description: "",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 3,
    title: "Formation",
    slug: "formation",
    category: "Training",
    summary:
      "Formations pratiques sur le no-code, l'IA et l'automatisation pour vos équipes.",
    description: "",
    deliverables: [
      "Parcours personnalise",
      "Exercices pratiques",
      "Support post-formation",
    ],
    duration_estimate: "1-3 jours",
    starting_price_text: "Sur devis",
    cta_label: "Voir les formations",
    cta_link: "/pro",
    sort_order: 3,
    seo_title: "",
    seo_description: "",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const fallbackCaseStudies: CaseStudy[] = [
  {
    id: 1,
    title: "Automatisation reporting hebdo",
    slug: "reporting-hebdo",
    client_type: "PME",
    problem:
      "Reporting manuel dispersé entre plusieurs outils et trop chronophage.",
    solution:
      "Automatisation des flux via Make + Airtable, consolidation des KPIs.",
    results: "10h/semaine économisées et meilleure fiabilité des données.",
    tools: ["Make", "Airtable", "Google Sheets"],
    cover_image: undefined,
    sort_order: 1,
    seo_title: "",
    seo_description: "",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 2,
    title: "CRM no-code pour agence",
    slug: "crm-agence",
    client_type: "Agence",
    problem:
      "Perte d'informations client et absence de suivi des opportunités.",
    solution: "Mise en place d'un CRM sur mesure et automatisations emails.",
    results: "Suivi unifié et cycle de vente accéléré.",
    tools: ["Notion", "Zapier"],
    cover_image: undefined,
    sort_order: 2,
    seo_title: "",
    seo_description: "",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 3,
    title: "Formation IA pour equipe terrain",
    slug: "formation-ia-terrain",
    client_type: "Retail",
    problem: "Equipe peu autonome sur les outils IA et no-code.",
    solution: "Formation sur mesure + support post-formation.",
    results: "Adoption rapide et reduction des taches repetitives.",
    tools: ["ChatGPT", "Notion"],
    cover_image: undefined,
    sort_order: 3,
    seo_title: "",
    seo_description: "",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const fallbackTrainings: Training[] = [
  {
    id: 1,
    title: "Formation No-code & Automatisation",
    slug: "formation-no-code-automatisation",
    summary:
      "Maîtriser les workflows Make/n8n pour automatiser vos tâches répétitives.",
    description:
      "Atelier intensif pour cartographier vos process, concevoir des automatisations fiables et maintenir vos scénarios.",
    audience: "Dirigeants, équipes ops, assistants",
    format: "Présentiel ou distanciel",
    duration: "1 jour (7h)",
    objectives: [
      "Identifier les gains rapides",
      "Concevoir un workflow robuste",
      "Déployer et monitorer les automatisations",
    ],
    prerequisites: ["Aucun prérequis technique", "Accès à vos outils"],
    program_outline:
      "Diagnostic, design des workflows, atelier Make/n8n, tests & monitoring.",
    cta_label: "Demander le programme",
    cta_link: "/contact",
    sort_order: 1,
    seo_title: "Formation no-code & automatisation",
    seo_description:
      "Formation pratique pour automatiser vos process avec Make/n8n. Objectifs clairs, résultats rapides.",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 2,
    title: "Formation IA pour équipes terrain",
    slug: "formation-ia-equipes-terrain",
    summary:
      "Apprendre à intégrer l'IA dans les tâches quotidiennes sans complexité.",
    description:
      "Sessions concrètes pour accélérer la rédaction, l'analyse et la prise de décision avec l'IA.",
    audience: "Commerciaux, managers, équipes terrain",
    format: "Présentiel",
    duration: "1 jour (7h)",
    objectives: [
      "Écrire plus vite et mieux",
      "Analyser des données sans friction",
      "Créer des routines IA utiles",
    ],
    prerequisites: ["Ordinateur portable", "Cas d'usage interne"],
    program_outline:
      "Cas d'usage, prompts efficaces, assistants personnalisés, plan d'adoption.",
    cta_label: "Réserver une session",
    cta_link: "/contact",
    sort_order: 2,
    seo_title: "Formation IA pour équipes terrain",
    seo_description:
      "Parcours IA opérationnel pour équipes terrain : prompts, routines, adoption rapide.",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 3,
    title: "Atelier Process & Roadmap digitale",
    slug: "atelier-process-roadmap",
    summary:
      "Cadrer les priorités, définir les KPI et livrer une feuille de route actionnable.",
    description:
      "Atelier stratégique pour aligner les équipes, prioriser les initiatives et estimer le ROI.",
    audience: "Direction, équipes projet",
    format: "Présentiel ou distanciel",
    duration: "0,5 jour (4h)",
    objectives: [
      "Prioriser les initiatives",
      "Chiffrer les gains",
      "Planifier les prochaines étapes",
    ],
    prerequisites: ["Accès aux KPIs clés", "Temps de préparation"],
    program_outline:
      "Interview, mapping, scoring ROI, restitution roadmap & quick wins.",
    cta_label: "Planifier l'atelier",
    cta_link: "/contact",
    sort_order: 3,
    seo_title: "Atelier process & roadmap digitale",
    seo_description:
      "Atelier express pour prioriser les automatisations et délivrer une roadmap ROI.",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];
